# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('publish', 'Publish'), ('export', 'Export'), ('import', 'Import')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(help_text='Module/Feature where action occurred', max_length=50, verbose_name='Module')),
                ('entity_type', models.CharField(help_text='Type of object affected (e.g., Student, Course)', max_length=50, verbose_name='Entity Type')),
                ('entity_id', models.CharField(blank=True, max_length=50, verbose_name='Entity ID')),
                ('entity_repr', models.CharField(blank=True, help_text='Human-readable representation of the entity', max_length=200, verbose_name='Entity Representation')),
                ('before_data', models.JSONField(blank=True, default=dict, help_text='Data before the change', verbose_name='Before Data')),
                ('after_data', models.JSONField(blank=True, default=dict, help_text='Data after the change', verbose_name='After Data')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx')],
            },
        ),
    ]
