# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('waiting', 'Waiting List'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='enrolled', max_length=20, verbose_name='Enrollment Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('dropped_at', models.DateTimeField(blank=True, null=True, verbose_name='Dropped At')),
                ('drop_reason', models.TextField(blank=True, verbose_name='Drop Reason')),
                ('total_classes', models.PositiveIntegerField(default=0, verbose_name='Total Classes')),
                ('attended_classes', models.PositiveIntegerField(default=0, verbose_name='Attended Classes')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Attendance Percentage')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Total Score')),
                ('letter_grade', models.CharField(blank=True, max_length=3, verbose_name='Letter Grade')),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Grade Point')),
                ('pass_fail_status', models.CharField(blank=True, max_length=10, verbose_name='Pass/Fail Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseoffering', verbose_name='Course Offering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course_offering')},
            },
        ),
    ]
