# Generated by Django 6.0.3 on 2026-04-02 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='total_score',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Final Score'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='result_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('published', 'Published')], default='pending', max_length=20, verbose_name='Result Status'),
        ),
    ]
