# Generated by Django 6.0.3 on 2026-04-06 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_enrollment_total_score_enrollment_final_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='grade_point',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='letter_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='pass_fail_status',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='_final_score',
            field=models.DecimalField(blank=True, db_column='final_score', decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Final Score (Deprecated)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='_grade_point',
            field=models.DecimalField(blank=True, db_column='grade_point', decimal_places=2, max_digits=3, null=True, verbose_name='Grade Point (Deprecated)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='_letter_grade',
            field=models.CharField(blank=True, db_column='letter_grade', max_length=3, verbose_name='Letter Grade (Deprecated)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='_pass_fail_status',
            field=models.CharField(blank=True, db_column='pass_fail_status', max_length=10, verbose_name='Pass/Fail Status (Deprecated)'),
        ),
    ]
