# Generated by Django 6.0.3 on 2026-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_remove_enrollment_final_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='attended_classes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Attended Classes'),
        ),
    ]
