# Generated by Django 6.0.3 on 2026-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_token',
        ),
    ]
