# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_zh', models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_zh', models.TextField(blank=True, verbose_name='Content (Chinese)')),
                ('summary_en', models.TextField(blank=True, help_text='Short summary for preview cards', verbose_name='Summary (English)')),
                ('summary_zh', models.TextField(blank=True, verbose_name='Summary (Chinese)')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('teachers', 'Teachers Only'), ('admin', 'Administrators Only')], default='all', max_length=20, verbose_name='Target Audience')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of announcements list', verbose_name='Is Pinned')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='Attachment')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
    ]
