# Generated by Django 6.0.3 on 2026-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Department Name (English)')),
                ('name_zh', models.CharField(blank=True, max_length=100, verbose_name='Department Name (Chinese)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Department Code')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_zh', models.TextField(blank=True, verbose_name='Description (Chinese)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
    ]
