# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('programs', '0001_initial'),
        ('semesters', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('batch_year', models.CharField(max_length=10, verbose_name='Batch/Entry Year')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Nationality')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='ID/Passport Number')),
                ('guardian_name', models.CharField(blank=True, max_length=100, verbose_name='Guardian Name')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='Guardian Phone')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='Guardian Email')),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, verbose_name='Relationship to Guardian')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Admission Date')),
                ('expected_graduation', models.DateField(blank=True, null=True, verbose_name='Expected Graduation Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('transferred', 'Transferred'), ('dropped_out', 'Dropped Out')], default='active', max_length=20, verbose_name='Status')),
                ('total_credits_earned', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Total Credits Earned')),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='CGPA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to='teachers.teacher', verbose_name='Academic Advisor')),
                ('current_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='semesters.semester', verbose_name='Current Semester')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='departments.department', verbose_name='Department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.program', verbose_name='Program/Major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['student_no'],
            },
        ),
    ]
