# Generated by Django 6.0.3 on 2026-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('semester_type', models.CharField(choices=[('fall', 'Fall Semester'), ('spring', 'Spring Semester'), ('summer', 'Summer Semester'), ('winter', 'Winter Semester')], default='fall', max_length=20, verbose_name='Semester Type')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name (English)')),
                ('name_zh', models.CharField(blank=True, max_length=50, verbose_name='Name (Chinese)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('registration_start', models.DateField(blank=True, null=True, verbose_name='Registration Start')),
                ('registration_end', models.DateField(blank=True, null=True, verbose_name='Registration End')),
                ('grade_entry_start', models.DateField(blank=True, null=True, verbose_name='Grade Entry Start')),
                ('grade_entry_end', models.DateField(blank=True, null=True, verbose_name='Grade Entry End')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semesters',
                'ordering': ['-academic_year', 'semester_type'],
                'unique_together': {('academic_year', 'semester_type')},
            },
        ),
    ]
