# Generated by Django 6.0.3 on 2026-04-06 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0003_remove_enrollment_final_score_and_more'),
        ('semesters', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('attendance_recalc', 'Attendance Recalculation'), ('result_recalc', 'Result Recalculation'), ('gpa_recalc', 'GPA Calculation'), ('cgpa_recalc', 'CGPA Calculation'), ('warning_recalc', 'Warning Calculation'), ('final_result_calc', 'Final Result Calculation'), ('mark_sync', 'Marks Synchronization')], db_index=True, help_text='Type of calculation performed', max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='success', help_text='Result status of the calculation', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Human-readable summary of the operation')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured data about inputs, outputs, and intermediate values')),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is failed')),
                ('triggered_by_name', models.CharField(blank=True, help_text='Cached name of triggering user for historical reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of calculation in milliseconds', null=True)),
                ('course_offering', models.ForeignKey(blank=True, help_text='Course offering context', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logs', to='courses.courseoffering')),
                ('enrollment', models.ForeignKey(blank=True, help_text='Enrollment record for this calculation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logs', to='enrollments.enrollment')),
                ('semester', models.ForeignKey(blank=True, help_text='Semester context for this calculation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logs', to='semesters.semester')),
                ('student', models.ForeignKey(blank=True, help_text='Student associated with this calculation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logs', to='students.student')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered this calculation (null for system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'action_type', '-created_at'], name='core_system_student_f3be83_idx'), models.Index(fields=['enrollment', 'action_type', '-created_at'], name='core_system_enrollm_5461f5_idx'), models.Index(fields=['action_type', 'status', '-created_at'], name='core_system_action__b81310_idx'), models.Index(fields=['semester', 'action_type', '-created_at'], name='core_system_semeste_ec6623_idx')],
            },
        ),
    ]
