# Generated by Django 6.0.3 on 2026-04-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_calculation_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('result', 'Result Processing'), ('warning', 'Warning Generation'), ('attendance', 'Attendance Tracking')], max_length=20, verbose_name='Process Type')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('incomplete', 'Incomplete'), ('ready', 'Ready'), ('processing', 'Processing'), ('completed', 'Completed'), ('published', 'Published'), ('failed', 'Failed'), ('locked', 'Locked'), ('partial', 'Partial')], default='not_started', max_length=20, verbose_name='Status')),
                ('student_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Student ID')),
                ('enrollment_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Enrollment ID')),
                ('semester_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Semester ID')),
                ('course_offering_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Course Offering ID')),
                ('message', models.TextField(blank=True, verbose_name='Status Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Status Details')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_processing_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Status',
                'verbose_name_plural': 'Processing Statuses',
                'db_table': 'processing_statuses',
                'indexes': [models.Index(fields=['process_type', 'status'], name='processing__process_44052e_idx'), models.Index(fields=['student_id', 'process_type'], name='processing__student_0557f0_idx'), models.Index(fields=['enrollment_id', 'process_type'], name='processing__enrollm_14e027_idx'), models.Index(fields=['semester_id', 'process_type'], name='processing__semeste_8cb5f3_idx'), models.Index(fields=['updated_at'], name='processing__updated_810591_idx')],
            },
        ),
    ]
