# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('semesters', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('title_en', models.CharField(max_length=200, verbose_name='Course Title (English)')),
                ('title_zh', models.CharField(blank=True, max_length=200, verbose_name='Course Title (Chinese)')),
                ('credit_hours', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Credit Hours')),
                ('lecture_hours', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, verbose_name='Lecture Hours per Week')),
                ('lab_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Lab Hours per Week')),
                ('course_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Laboratory'), ('theory_lab', 'Theory + Lab'), ('seminar', 'Seminar'), ('project', 'Project'), ('internship', 'Internship'), ('thesis', 'Thesis/Dissertation')], default='theory', max_length=20, verbose_name='Course Type')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_zh', models.TextField(blank=True, verbose_name='Description (Chinese)')),
                ('learning_outcomes_en', models.TextField(blank=True, verbose_name='Learning Outcomes (English)')),
                ('learning_outcomes_zh', models.TextField(blank=True, verbose_name='Learning Outcomes (Chinese)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='departments.department', verbose_name='Department')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='is_prerequisite_for', to='courses.course', verbose_name='Prerequisites')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='01', help_text='e.g., 01, 02, A, B', max_length=20, verbose_name='Section')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Classroom')),
                ('day_of_week', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10, verbose_name='Day of Week')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('capacity', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='Enrolled Count')),
                ('waiting_count', models.PositiveIntegerField(default=0, verbose_name='Waiting List Count')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Registration'), ('in_progress', 'In Progress'), ('grading', 'Grading'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('is_grade_published', models.BooleanField(default=False, verbose_name='Grades Published')),
                ('grade_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Grades Published At')),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabi/%Y/%m/', verbose_name='Syllabus')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='courses.course', verbose_name='Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='semesters.semester', verbose_name='Semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='teachers.teacher', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'db_table': 'course_offerings',
                'ordering': ['semester', 'course__code', 'section_name'],
                'unique_together': {('course', 'semester', 'section_name')},
            },
        ),
    ]
