# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Component Name')),
                ('assessment_type', models.CharField(choices=[('attendance', 'Attendance'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('midterm', 'Midterm Exam'), ('lab', 'Lab Work'), ('project', 'Project'), ('presentation', 'Presentation'), ('final', 'Final Exam'), ('participation', 'Participation'), ('other', 'Other')], default='assignment', max_length=20, verbose_name='Assessment Type')),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='Percentage weight towards final grade', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Weight (%)')),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Score')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Scores Published')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='courses.courseoffering', verbose_name='Course Offering')),
            ],
            options={
                'verbose_name': 'Assessment Component',
                'verbose_name_plural': 'Assessment Components',
                'db_table': 'assessment_components',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Entered At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessmentcomponent', verbose_name='Assessment Component')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='enrollments.enrollment', verbose_name='Enrollment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_scores', to=settings.AUTH_USER_MODEL, verbose_name='Entered By')),
            ],
            options={
                'verbose_name': 'Assessment Score',
                'verbose_name_plural': 'Assessment Scores',
                'db_table': 'assessment_scores',
                'ordering': ['assessment_component__order'],
                'unique_together': {('enrollment', 'assessment_component')},
            },
        ),
    ]
