# Generated by Django 6.0.3 on 2026-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Policy Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('max_gpa', models.DecimalField(decimal_places=2, default=4.0, max_digits=3, verbose_name='Maximum GPA')),
                ('passing_grade_point', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Minimum Passing Grade Point')),
                ('gpa_warning_threshold', models.DecimalField(decimal_places=2, default=2.0, max_digits=3, verbose_name='GPA Warning Threshold')),
                ('cgpa_warning_threshold', models.DecimalField(decimal_places=2, default=2.0, max_digits=3, verbose_name='CGPA Warning Threshold')),
                ('attendance_warning_threshold', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, verbose_name='Attendance Warning Threshold (%)')),
                ('gpa_drop_warning_threshold', models.DecimalField(decimal_places=2, default=0.8, max_digits=3, verbose_name='GPA Drop Warning Threshold')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Policy',
                'verbose_name_plural': 'Grade Policies',
                'db_table': 'grade_policies',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True, verbose_name='Setting Key')),
                ('setting_value', models.TextField(verbose_name='Setting Value')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=20, verbose_name='Data Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Is Editable')),
                ('category', models.CharField(default='general', help_text='e.g., general, academic, grading, email', max_length=50, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['category', 'setting_key'],
            },
        ),
    ]
