# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Program Name (English)')),
                ('name_zh', models.CharField(blank=True, max_length=100, verbose_name='Program Name (Chinese)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Program Code')),
                ('degree_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='bachelor', max_length=20, verbose_name='Degree Level')),
                ('duration_years', models.PositiveSmallIntegerField(default=4, verbose_name='Duration (Years)')),
                ('total_credits', models.PositiveSmallIntegerField(default=120, verbose_name='Total Credits Required')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_zh', models.TextField(blank=True, verbose_name='Description (Chinese)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='departments.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'ordering': ['department', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_semester', models.PositiveSmallIntegerField(help_text='The semester this course is recommended for (1, 2, 3, etc.)', verbose_name='Recommended Semester')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is Required')),
                ('course_nature', models.CharField(choices=[('required', 'Required'), ('elective', 'Elective'), ('optional', 'Optional')], default='required', max_length=20, verbose_name='Course Nature')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_curricula', to='courses.course', verbose_name='Course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Curriculum Course',
                'verbose_name_plural': 'Curriculum Courses',
                'db_table': 'curriculum_courses',
                'ordering': ['program', 'recommended_semester', 'course__code'],
                'unique_together': {('program', 'course')},
            },
        ),
    ]
