# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Rule Code')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('gpa', 'GPA'), ('cgpa', 'CGPA'), ('course_failures', 'Course Failures'), ('missing_assessment', 'Missing Assessment'), ('gpa_trend', 'GPA Trend'), ('teacher_flag', 'Teacher Flag')], max_length=30, verbose_name='Category')),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='Threshold value for triggering this rule', max_digits=6, verbose_name='Threshold Value')),
                ('comparison_operator', models.CharField(default='<', help_text='Comparison operator: <, >, <=, >=, ==', max_length=10, verbose_name='Comparison')),
                ('weight', models.DecimalField(decimal_places=2, default=10.0, help_text='Weight contribution to overall risk score', max_digits=4, verbose_name='Risk Weight')),
                ('severity', models.CharField(choices=[('yellow', 'Yellow - Mild'), ('orange', 'Orange - Serious'), ('red', 'Red - Critical')], default='yellow', max_length=10, verbose_name='Warning Severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Evaluation Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Early Warning Rule',
                'verbose_name_plural': 'Early Warning Rules',
                'db_table': 'early_warning_rules',
                'ordering': ['order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, help_text='0-100 scale, higher is more at risk', max_digits=5, verbose_name='Overall Risk Score')),
                ('warning_level', models.CharField(choices=[('green', 'Green - Stable'), ('yellow', 'Yellow - Mild Warning'), ('orange', 'Orange - Serious Warning'), ('red', 'Red - Critical Warning')], default='green', max_length=20, verbose_name='Warning Level')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of triggered risk factors with details', verbose_name='Risk Factors')),
                ('attendance_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Attendance Risk Score')),
                ('gpa_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='GPA Risk Score')),
                ('course_failure_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Course Failure Risk Score')),
                ('trend_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Trend Risk Score')),
                ('missing_assessment_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Missing Assessment Risk Score')),
                ('teacher_flag_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Teacher Flag Risk Score')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of suggested interventions', verbose_name='Recommendations')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Is Acknowledged by Student')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_results', to='semesters.semester', verbose_name='Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_results', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Early Warning Result',
                'verbose_name_plural': 'Early Warning Results',
                'db_table': 'early_warning_results',
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
