# Generated by Django 6.0.3 on 2026-04-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('warnings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('from_level', models.CharField(choices=[('green', 'Green - Stable'), ('yellow', 'Yellow - Mild Warning'), ('orange', 'Orange - Serious Warning'), ('red', 'Red - Critical Warning')], max_length=20, verbose_name='From Level')),
                ('to_level', models.CharField(choices=[('green', 'Green - Stable'), ('yellow', 'Yellow - Mild Warning'), ('orange', 'Orange - Serious Warning'), ('red', 'Red - Critical Warning')], max_length=20, verbose_name='To Level')),
                ('days_without_improvement', models.PositiveIntegerField(default=7, help_text='Number of days to wait before escalating if no improvement', verbose_name='Days Without Improvement')),
                ('requires_intervention_attempt', models.BooleanField(default=True, help_text='Only escalate if at least one intervention was attempted', verbose_name='Requires Intervention Attempt')),
                ('auto_notify_parents', models.BooleanField(default=False, verbose_name='Auto-notify Parents')),
                ('auto_notify_advisor', models.BooleanField(default=True, verbose_name='Auto-notify Advisor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Warning Escalation Rule',
                'verbose_name_plural': 'Warning Escalation Rules',
                'db_table': 'warning_escalation_rules',
            },
        ),
        migrations.CreateModel(
            name='ParentGuardianNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Parent/Guardian Name')),
                ('relationship', models.CharField(help_text='e.g., Father, Mother, Guardian', max_length=50, verbose_name='Relationship')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('letter', 'Physical Letter')], max_length=20, verbose_name='Notification Method')),
                ('message_content', models.TextField(verbose_name='Message Content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('response_received', models.TextField(blank=True, verbose_name='Response Received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_parent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sent By')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to='warnings.earlywarningresult', verbose_name='Related Warning')),
            ],
            options={
                'verbose_name': 'Parent/Guardian Notification',
                'verbose_name_plural': 'Parent/Guardian Notifications',
                'db_table': 'parent_guardian_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('attendance_record', 'Attendance Record'), ('grade_record', 'Grade Record'), ('assignment_missing', 'Missing Assignment'), ('teacher_observation', 'Teacher Observation'), ('behavioral_report', 'Behavioral Report'), ('screenshot', 'Screenshot'), ('document', 'Document'), ('other', 'Other')], max_length=30, verbose_name='Evidence Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='warning_evidence/%Y/%m/', verbose_name='File Attachment')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of relevant data at time of warning', verbose_name='Data Snapshot')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Captured By')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='warnings.earlywarningresult', verbose_name='Related Warning')),
            ],
            options={
                'verbose_name': 'Warning Evidence',
                'verbose_name_plural': 'Warning Evidence',
                'db_table': 'warning_evidence',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Warning Created'), ('level_changed', 'Warning Level Changed'), ('escalated', 'Warning Escalated'), ('de_escalated', 'Warning De-escalated'), ('acknowledged', 'Warning Acknowledged'), ('resolved', 'Warning Resolved'), ('reopened', 'Warning Reopened'), ('intervention_added', 'Intervention Added'), ('intervention_completed', 'Intervention Completed'), ('notes_added', 'Notes Added'), ('auto_calculated', 'Auto-calculated')], max_length=30, verbose_name='Change Type')),
                ('previous_level', models.CharField(blank=True, max_length=20, verbose_name='Previous Warning Level')),
                ('new_level', models.CharField(blank=True, max_length=20, verbose_name='New Warning Level')),
                ('previous_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Previous Risk Score')),
                ('new_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='New Risk Score')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Triggered By')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='warnings.earlywarningresult', verbose_name='Related Warning')),
            ],
            options={
                'verbose_name': 'Warning History',
                'verbose_name_plural': 'Warning History',
                'db_table': 'warning_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('meeting_scheduled', 'Meeting Scheduled'), ('meeting_completed', 'Meeting Completed'), ('tutoring_assigned', 'Tutoring Assigned'), ('study_plan_created', 'Study Plan Created'), ('advisor_consultation', 'Advisor Consultation'), ('parent_notified', 'Parent/Guardian Notified'), ('attendance_contract', 'Attendance Contract Signed'), ('academic_probation', 'Academic Probation Assigned'), ('course_withdrawal', 'Course Withdrawal Recommended'), ('counseling_referral', 'Counseling Referral'), ('other', 'Other Action')], max_length=30, verbose_name='Intervention Type')),
                ('description', models.TextField(help_text='Detailed description of the intervention', verbose_name='Description')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('follow_up_needed', 'Follow-up Needed')], default='planned', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('outcome_notes', models.TextField(blank=True, help_text='Results and observations after intervention', verbose_name='Outcome Notes')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Follow-up Date')),
                ('is_effective', models.BooleanField(blank=True, help_text='Whether the intervention achieved desired results', null=True, verbose_name='Was Effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to='teachers.teacher', verbose_name='Assigned To')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='warnings.earlywarningresult', verbose_name='Related Warning')),
            ],
            options={
                'verbose_name': 'Warning Intervention',
                'verbose_name_plural': 'Warning Interventions',
                'db_table': 'warning_interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_type', models.CharField(choices=[('improved_performance', 'Improved Performance'), ('attendance_recovered', 'Attendance Recovered'), ('completed_intervention', 'Completed Intervention Program'), ('withdrawal_approved', 'Course Withdrawal Approved'), ('semester_completed', 'Semester Completed'), ('transferred', 'Student Transferred'), ('other', 'Other')], max_length=30, verbose_name='Resolution Type')),
                ('resolution_notes', models.TextField(help_text='How the warning was resolved', verbose_name='Resolution Notes')),
                ('final_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Final Risk Score')),
                ('improvement_metrics', models.JSONField(blank=True, default=dict, help_text='Quantifiable improvements (attendance %, GPA change, etc.)', verbose_name='Improvement Metrics')),
                ('requires_monitoring', models.BooleanField(default=False, verbose_name='Requires Continued Monitoring')),
                ('monitoring_end_date', models.DateField(blank=True, null=True, verbose_name='Monitoring End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_warnings', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('warning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='warnings.earlywarningresult', verbose_name='Related Warning')),
            ],
            options={
                'verbose_name': 'Warning Resolution',
                'verbose_name_plural': 'Warning Resolutions',
                'db_table': 'warning_resolutions',
            },
        ),
    ]
