# Generated by Django 6.0.3 on 2026-04-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warnings', '0002_warningescalationrule_parentguardiannotification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentGuardianNotification',
        ),
    ]
