# Generated by Django 6.0.3 on 2026-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warnings', '0003_delete_parentguardiannotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlywarningresult',
            name='cgpa_risk_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='CGPA Risk Score'),
        ),
    ]
