# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_no', models.CharField(max_length=20, unique=True, verbose_name='Teacher ID')),
                ('title', models.CharField(choices=[('lecturer', 'Lecturer'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('senior_professor', 'Senior Professor'), ('instructor', 'Instructor'), ('adjunct', 'Adjunct Professor'), ('visiting', 'Visiting Professor')], default='lecturer', max_length=30, verbose_name='Title')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization/Research Area')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='Office Location')),
                ('office_hours', models.TextField(blank=True, help_text='e.g., Mon 10:00-12:00, Wed 14:00-16:00', verbose_name='Office Hours')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('retired', 'Retired'), ('resigned', 'Resigned')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='departments.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['teacher_no'],
            },
        ),
    ]
