# Generated by Django 6.0.3 on 2026-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='awards_and_honors',
            field=models.TextField(blank=True, help_text='Awards, recognitions, and honors received', verbose_name='Awards and Honors'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_background',
            field=models.TextField(blank=True, help_text='Your academic degrees and educational history', verbose_name='Education Background'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='professional_experience',
            field=models.TextField(blank=True, help_text='Your work experience and professional background', verbose_name='Professional Experience'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='publications',
            field=models.TextField(blank=True, help_text='List your key publications, papers, and research works', verbose_name='Publications'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='research_abilities',
            field=models.TextField(blank=True, help_text='List your research skills, methodologies, and technical abilities', verbose_name='Research Abilities'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Describe your research interests and areas of expertise', verbose_name='Research Interests'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_interests',
            field=models.TextField(blank=True, help_text='Courses and subjects you are interested in teaching', verbose_name='Teaching Interests'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='website',
            field=models.URLField(blank=True, verbose_name='Personal Website'),
        ),
    ]
