# Generated by Django 6.0.3 on 2026-03-27 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_zh', models.CharField(blank=True, max_length=200, verbose_name='Title (Chinese)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_zh', models.TextField(blank=True, verbose_name='Content (Chinese)')),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('academic', 'Academic'), ('warning', 'Warning'), ('grade', 'Grade'), ('attendance', 'Attendance'), ('message', 'Message'), ('announcement', 'Announcement')], default='system', max_length=20, verbose_name='Notification Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('related_object_type', models.CharField(blank=True, help_text='e.g., enrollment, course, warning', max_length=50, verbose_name='Related Object Type')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Related Object ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_emailed', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='Emailed At')),
                ('action_url', models.URLField(blank=True, help_text='Optional URL for user to take action', verbose_name='Action URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
